fix: update readme content
linuxdeepin/dde-account-faces pull request #20
Opened 2022-09-09 03:02 UTC by ssk-wh

update readme content

Log: update readme content

2022-09-09 03:08 UTC, BLumia requested changes

2022-09-09 03:08 UTC, BLumia commented on README.md
>  * [IRC channel](https://webchat.freenode.net/?channels=deepin)
```suggestion
```

2022-09-09 03:08 UTC, BLumia commented on README.zh_CN.md
>  * [IRC channel](https://webchat.freenode.net/?channels=deepin)
```suggestion
```

2022-09-09 03:43 UTC, robertkill submitted a review, later dismissed

2022-09-09 05:20 UTC, BLumia submitted a review, later dismissed

2022-09-26 06:10 UTC, shao-jun approved these changes

2022-09-26 07:15 UTC, ssk-wh commented
/merge

2022-09-26 08:11 UTC, shao-jun approved these changes

2022-09-26 08:11 UTC, ssk-wh commented
/merge

2022-09-26 08:12 UTC, merged